export const contractions = {
  "can't": ["can not"],
  "could've": ["could have"],
  "couldn't": ["could not"],
  "didn't": ["did not"],
  "doesn't": ["does not"],
  "don't": ["do not"],
  "hadn't": ["had not"],
  "hasn't": ["has not"],
  "haven't": ["have not"],
  "he'd": ["he had", "he would"],
  "he'll": ["he will"],
  "he's": ["he is", "he has"],
  "how'd": ["how did", "how would"],
  "how'll": ["how will"],
  "how's": ["how is", "how has"],
  "I'd": ["I had", "I would"],
  "I'll": ["I will"],
  "I'm": ["I am"],
  "I've": ["I have"],
  "isn't": ["is not"],
  "it'd": ["it had", "it would"],
  "it'll": ["it will"],
  "it's": ["it is", "it has"],
  "let's": ["let us"],
  "might've": ["might have"],
  "mightn't": ["might not"],
  "must've": ["must have"],
  "mustn't": ["must not"],
  "needn't": ["need not"],
  "oughtn't": ["ought not"],
  "shan't": ["shall not"],
  "she'd": ["she had", "she would"],
  "she'll": ["she will"],
  "she's": ["she is", "she has"],
  "should've": ["should have"],
  "shouldn't": ["should not"],
  "that'd": ["that would"],
  "that's": ["that is", "that has"],
  "there'd": ["there had", "there would"],
  "there's": ["there is", "there has"],
  "they'd": ["they had", "they would"],
  "they'll": ["they will"],
  "they're": ["they are"],
  "they've": ["they have"],
  "wasn't": ["was not"],
  "we'd": ["we had", "we would"],
  "we'll": ["we will"],
  "we're": ["we are"],
  "we've": ["we have"],
  "weren't": ["were not"],
  "what'll": ["what will"],
  "what're": ["what are"],
  "what's": ["what is", "what has"],
  "what've": ["what have"],
  "where's": ["where is", "where has"],
  "who'd": ["who had", "who would"],
  "who'll": ["who will"],
  "who're": ["who are"],
  "who's": ["who is", "who has"],
  "who've": ["who have"],
  "won't": ["will not"],
  "would've": ["would have"],
  "wouldn't": ["would not"],
  "you'd": ["you had", "you would"],
  "you'll": ["you will"],
  "you're": ["you are"],
  "you've": ["you have"],
};
